/-
 Copyright Cedar Contributors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-/

import Cedar.SymCC.Concretizer
import Cedar.SymCC.Decoder
import Cedar.SymCC.Extractor
import Cedar.SymCC.Interpretation
import Cedar.SymCC.Solver
import Cedar.SymCC.Verifier

namespace Cedar.SymCC

open Cedar.Spec

/--
Given some `asserts` and their corresponding symbolic environment `εnv`,
calls the SMT solver (if necessary) on an SMTLib encoding of `asserts` and
returns `none` if the result is unsatisfiable. Otherwise returns `some I`
containing a counterexample interpretation `I`. The `asserts` are expected to
be well-formed with respect to `εnv` according to `Cedar.SymCC.Term.WellFormed`.
This call resets the solver.
-/
def checkSatAsserts (asserts : Asserts) (εnv : SymEnv) : SolverM (Option Interpretation) := do
  if asserts.any (· == false) then
    Solver.reset
    pure .none
  else if asserts.all (· == true) then
    Solver.reset
    pure (.some (Decoder.defaultInterpretation εnv.entities))
  else
    let enc ← Encoder.encode asserts εnv (produceModels := true)
    match (← Solver.checkSat) with
    | .unsat   => pure .none
    | .sat     =>
      let model ← Solver.getModel
      match Decoder.decode model enc with
      | .ok I      => -- validate the model
        for t in asserts do
          if t.interpret I != true then
            throw (IO.userError s!"Model violates assertion {reprStr t}: {model}")
        pure (.some I)
      | .error msg => throw (IO.userError s!"Model decoding failed: {msg}\n {model}")
    | .unknown => throw (IO.userError s!"Solver returned unknown.")

/--
Given policies `ps` (in their post-typecheck forms), some `asserts`, and the
corresponding symbolic environment `εnv`, calls the SMT solver (if necessary) on
an SMTLib encoding of `asserts` and returns `none` if the result is
unsatisfiable. Otherwise returns `some env` containing a counterexample
environment such that evaluating `ps` in `env` violates the property verified by
`asserts`.

The `asserts` are expected to be well-formed with respect to `εnv` according to
`Cedar.SymCC.Term.WellFormed`. They must encode a property of policies `pc`.
Specifically, for each term `t ∈ asserts`, there must be a set of expressions
`xs` such that each `x ∈ xs` is a subexpression of `p ∈ ps`, and the meaning of
`t` is a function of the meaning of `xs`. This ensures that findings generated
by `solve` are sound and complete.
-/
def satAsserts? (ps : Policies) (asserts : Asserts) (εnv : SymEnv) : SolverM (Option Env) := do
  match ← checkSatAsserts asserts εnv with
  | .none   => pure none
  | .some I =>
    match εnv.extract? (ps.map Policy.toExpr) I with
    | .some env => pure (some env)
    | .none     => throw (IO.userError s!"Extraction failed.")

/--
Given policies `ps`, a verification condition generator `vc`, and a symbolic
environment `εnv`, calls the SMT solver (if necessary) on an SMTLib encoding of
`vc εnv` and returns `none` if the result is unsatisfiable. Otherwise
returns `some env` containing a counterexample environment such that
evaluating `ps` in `env` violates the property verified by `vc`.

The function `vc` is expected to produce a list of terms type .bool that are
well-formed with respect to `εnv` according to `Cedar.SymCC.Term.WellFormed`.
These terms must encode a property of policies `pc`.  Specifically, for each
term `t ∈ vc εnv`, there must be a set of expressions `xs` such that each
`x ∈ xs` is a subexpression of `p ∈ ps`, and the meaning of `t` is a function of
the meaning of `xs`.  This ensures that findings generated by `solve` are sound
and complete.

This call resets the solver.
-/
def sat? (ps : Policies) (vc : SymEnv → Result Asserts) (εnv : SymEnv) : SolverM (Option Env) :=
  match vc εnv with
  | .ok asserts => satAsserts? ps asserts εnv
  | .error err => throw (IO.userError s!"SymCC failed: {reprStr err}.")

/--
Given some `asserts` and their corresponding symbolic environment `εnv`,
calls the SMT solver (if necessary) on an SMTLib encoding of `asserts` and
returns `true` iff the result is unsatisfiable. The `asserts` are expected to
be well-formed with respect to `εnv` according to `Cedar.SymCC.Term.WellFormed`.
This call resets the solver.
-/
def checkUnsatAsserts (asserts : Asserts) (εnv : SymEnv) : SolverM Bool := do
  if asserts.any (· == false) then
    Solver.reset
    pure true
  else if asserts.all (· == true) then
    Solver.reset
    pure false
  else
    let _ ← Encoder.encode asserts εnv (produceModels := false)
    match (← Solver.checkSat) with
    | .unsat   => pure true
    | .sat     => pure false
    | .unknown => throw (IO.userError s!"Solver returned unknown.")

/--
Given a verification condition generator `vc` and a symbolic environment `εnv`,
calls the SMT solver (if necessary) on an SMTLib encoding of `vc εnv` and
returns `true` iff the result is unsatisfiable. The function `vc` is expected to
produce a list of terms type .bool that are well-formed with respect to `εnv`
according to `Cedar.SymCC.Term.WellFormed`. This call resets the solver.
-/
def checkUnsat (vc : SymEnv → Result Asserts) (εnv : SymEnv) : SolverM Bool := do
  match vc εnv with
  | .ok asserts => checkUnsatAsserts asserts εnv
  | .error err => throw (IO.userError s!"SymCC failed: {reprStr err}.")
