/*
 * Copyright Cedar Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#![no_main]
use cedar_drt::logger::initialize_log;
use cedar_drt_inner::{
    fuzz_target,
    symcc::{SinglePolicyFuzzTargetInput, assert_that_asserts_match},
};
use cedar_lean_ffi::CedarLeanFfi;
use cedar_policy_symcc::{CompiledPolicySet, always_allows_asserts};

// Fuzz target checking that Asserts (`Term`s) generated by Lean and Rust SymCC
// implementations for AlwaysAllows are equivalent
fuzz_target!(|input: SinglePolicyFuzzTargetInput<32>| {
    initialize_log();
    if let Ok((schema, policyset)) = input.into_inputs_as_pset() {
        let lean_ffi = CedarLeanFfi::new();
        let lean_schema = lean_ffi.load_lean_schema_object(&schema).unwrap();
        for req_env in schema.request_envs() {
            if let Ok(compiled_policies) = CompiledPolicySet::compile(&policyset, &req_env, &schema)
            {
                let rust_asserts = always_allows_asserts(&compiled_policies);
                let lean_asserts = lean_ffi
                    .asserts_of_check_always_allows(
                        &compiled_policies.policies().clone().try_into().unwrap(),
                        lean_schema.clone(),
                        &req_env,
                    )
                    // should succeed on the post-typecheck policies that were successfully produced by `CompiledPolicySet::compile()`
                    .unwrap()
                    .unwrap();
                assert_that_asserts_match(rust_asserts, lean_asserts);
            }
        }
    }
});
