/*
 * Copyright Cedar Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#![no_main]
use cedar_drt::logger::initialize_log;
use cedar_drt_inner::{
    fuzz_target,
    symcc::{TwoPolicyFuzzTargetInput, assert_that_asserts_match},
};

use cedar_lean_ffi::CedarLeanFfi;
use cedar_policy::{Policy, Schema};
use cedar_policy_symcc::{CompiledPolicy, matches_equivalent_asserts};

use log::debug;
use std::convert::TryFrom;

// Fuzz target checking that Asserts (`Term`s) generated by Lean and Rust SymCC
// implementations for MatchesEquivalent are equivalent
fuzz_target!(|input: TwoPolicyFuzzTargetInput| {
    initialize_log();
    let lean_ffi = CedarLeanFfi::new();
    let policy1: Policy = input.policy1.into();
    let policy2: Policy = input.policy2.into();
    debug!("Schema: {}\n", input.schema.schemafile_string());
    debug!("Policy1: {policy1}\n");
    debug!("Policy2: {policy2}\n");

    if let Ok(schema) = Schema::try_from(input.schema) {
        let lean_schema = lean_ffi.load_lean_schema_object(&schema).unwrap();
        for req_env in schema.request_envs() {
            if let Ok(cp1) = CompiledPolicy::compile(&policy1, &req_env, &schema)
                && let Ok(cp2) = CompiledPolicy::compile(&policy2, &req_env, &schema)
            {
                let rust_asserts = matches_equivalent_asserts(&cp1, &cp2);
                let lean_asserts = lean_ffi
                    .asserts_of_check_matches_equivalent(
                        &cp1.policy().clone().try_into().unwrap(),
                        &cp2.policy().clone().try_into().unwrap(),
                        lean_schema.clone(),
                        &req_env,
                    )
                    // should succeed on the post-typecheck policies that were successfully produced by `CompiledPolicy::compile()`
                    .unwrap()
                    .unwrap();
                assert_that_asserts_match(rust_asserts, lean_asserts);
            }
        }
    }
});
