/*
 * Copyright Cedar Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#![no_main]
use cedar_drt::logger::initialize_log;
use cedar_drt_inner::{
    fuzz_target,
    symcc::{TwoPolicyFuzzTargetInput, assert_that_asserts_match},
};

use cedar_lean_ffi::CedarLeanFfi;
use cedar_policy::{Policy, PolicySet, Schema};
use cedar_policy_symcc::{CompiledPolicySet, disjoint_asserts};

use log::debug;
use std::convert::TryFrom;

// Fuzz target checking that Asserts (`Term`s) generated by Lean and Rust SymCC
// implementations for Disjoint are equivalent
fuzz_target!(|input: TwoPolicyFuzzTargetInput| {
    initialize_log();
    let lean_ffi = CedarLeanFfi::new();
    let mut policyset1 = PolicySet::new();
    let policy1: Policy = input.policy1.into();
    let mut policyset2 = PolicySet::new();
    let policy2: Policy = input.policy2.into();
    debug!("Schema: {}\n", input.schema.schemafile_string());
    debug!("Policy1: {policy1}\n");
    debug!("Policy2: {policy2}\n");
    policyset1.add(policy1).unwrap();
    policyset2.add(policy2).unwrap();

    if let Ok(schema) = Schema::try_from(input.schema) {
        let lean_schema = lean_ffi.load_lean_schema_object(&schema).unwrap();
        for req_env in schema.request_envs() {
            // The validator DRT property we've been testing is that
            // rust_passes_validation => lean_passes_validation
            // So, we run the Rust validator first (as part of `compile()`) and
            // obtain post-typecheck, well-typed policies (available as
            // `.policies()` on the `CompiledPolicySet`.) These policies should
            // be also well-typed according to Lean.
            if let Ok(cpset1) = CompiledPolicySet::compile(&policyset1, &req_env, &schema)
                && let Ok(cpset2) = CompiledPolicySet::compile(&policyset2, &req_env, &schema)
            {
                let rust_asserts = disjoint_asserts(&cpset1, &cpset2);
                let lean_asserts = lean_ffi
                    .asserts_of_check_disjoint(
                        &cpset1.policies().clone().try_into().unwrap(),
                        &cpset2.policies().clone().try_into().unwrap(),
                        lean_schema.clone(),
                        &req_env,
                    )
                    // should succeed on the post-typecheck policies that were successfully produced by `CompiledPolicySet::compile()`
                    .unwrap()
                    .unwrap();
                assert_that_asserts_match(rust_asserts, lean_asserts);
            }
        }
    }
});
