/-
 Copyright Cedar Contributors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-/

import Cedar.SymCC.SatUnsat
import Cedar.SymCC.Solver
import Cedar.SymCCOpt.CompiledPolicies
import Cedar.SymCCOpt.Extractor

namespace Cedar.SymCC

open Cedar.Spec

/--
Given compiled policies `cpss` and some `asserts`, calls the SMT solver (if
necessary) on an SMTLib encoding of `asserts` and returns `none` if the result
is unsatisfiable. Otherwise returns `some env` containing a counterexample
environment such that evaluating `cpss` in `env` violates the property verified
by `asserts`.

The `asserts` are expected to be well-formed with respect to the `εnv` which
`cpss` where compiled for, according to `Cedar.SymCC.Term.WellFormed`.
(Caller guarantees that all of the `cpss` were compiled for the same `εnv`.)
They must encode a property of policies `pc`.
Specifically, for each term `t ∈ asserts`, there must be a set of expressions
`xs` such that each `x ∈ xs` is a subexpression of `p ∈ ps`, where `ps` are the
(post-typecheck) policies that were compiled to `cpss`, and the meaning of `t` is
a function of the meaning of `xs`. This ensures that findings generated by
`solve` are sound and complete.
-/
def satAssertsOpt? (cpss : List CompiledPolicies) (asserts : Asserts) : SolverM (Option Env) := do
  match cpss with
  | [] => throw (IO.userError s!"satAssertsOpt? called with empty list of policies")
  | cps :: _ =>
  match ← checkSatAsserts asserts cps.εnv with
  | .none   => pure none
  | .some I =>
    match extractOpt? cpss I with
    | .some env => pure (some env)
    | .none     => throw (IO.userError s!"Extraction failed.")
