name: Build and Test Cedar Lean CLI

on:
  workflow_call:
    inputs:
      cedar_spec_ref:
        required: false
        default: "main"
        type: string
      cedar_policy_ref:
        required: false
        default: "main"
        type: string

jobs:
  build_and_test_drt:
    name: Build and Test Cedar Lean CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout cedar-spec
        uses: actions/checkout@v4
        with:
          repository: cedar-policy/cedar-spec
          ref: ${{ inputs.cedar_spec_ref }}
          path: ./cedar-spec
      - name: checkout cedar
        uses: actions/checkout@v4
        with:
          repository: cedar-policy/cedar
          path: ./cedar-spec/cedar
          ref: ${{ inputs.cedar_policy_ref }}
      - name: Setup Cargo config for local Cedar
        working-directory: ./cedar-spec/cedar-lean-ffi
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml << EOF
          [patch.crates-io]
          ccedar-policy = { path = "../cedar/cedar-policy" }
          EOF
      - name: Install Lean
        shell: bash
        run: |
              wget https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
              bash elan-init.sh -y
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler
      - name: Prepare Rust build
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: cargo fmt (cedar-lean-cli)
        working-directory: ./cedar-spec/cedar-lean-cli
        run: cargo fmt --all --check
      - name: Build Lean libraries
        working-directory: ./cedar-spec/cedar-lean-ffi
        run: source ~/.profile && ./build_lean_lib.sh
      - name: cargo build (cedar-lean-cli)
        working-directory: ./cedar-spec/cedar-lean-cli
        run: source ~/.profile && source ../cedar-lean-ffi/set_env_vars.sh && cargo build
